name: .NET

on:
  push:
    branches: [ master ]
    paths: [ TotalImage*/**, .github/workflows/** ]
  pull_request:
    branches: [ master ]
    paths: [ TotalImage*/**, .github/workflows/** ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v5.2.0
      with:
        dotnet-version: 10.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build -c Debug
    - uses: actions/upload-artifact@v7.0.1
      with:
        path: TotalImage/bin/Debug/net10.0-windows/publish/
